version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddopay
    ports:
      - "13306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  bank-service:
    build:
      context: .
      dockerfile: bank-service/Dockerfile
    container_name: bank-service
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend

  pos-service:
    build:
      context: .
      dockerfile: pos-service/Dockerfile
    container_name: pos-service
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend

  ddo-store-service:
    build:
      context: .
      dockerfile: ddo-store-service/Dockerfile
    container_name: ddo-store-service
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql_data: